spring:
  application:
    name: ai-zero-code
  datasource:
    url: jdbc:mysql://localhost:3306/ai_zero_code?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: "123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      username: "default"
      password: "123"
      ttl: 3600
  jackson:
    time-zone: Asia/Shanghai
  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  group-configs:
    - group: "default"
      packages-to-scan: "com.qiujie.aizerocode.controller"

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.qiujie.aizerocode.mapper: DEBUG
